# Generated by Django 5.0.1 on 2024-01-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SearchQuery",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("ip_address", models.GenericIPAddressField()),
                ("search_query", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SearchQueryCounter",
            fields=[
                (
                    "search_query",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("counter", models.IntegerField(default=0)),
            ],
        ),
    ]
